server.port=8082

management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://${DB_HOST:app-postgres.sql-trainer.svc.cluster.local}:${DB_PORT:5432}/${DB_NAME:appdb}
spring.datasource.username=${DB_USER:appuser}
spring.datasource.password=${DB_PASSWORD:app_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5

# таблицы лежат в схемах tasks и, возможно, public
spring.sql.init.mode=never
