apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: sql-trainer
type: Opaque
stringData:
  # App DB (r/w)
  APP_DB_NAME: appdb
  APP_DB_USER: appuser
  APP_DB_PASSWORD: app_pass

  # Training DB (read-only user, но саму роль создадим позже скриптом)
  TRAIN_DB_NAME: training
  TRAIN_DB_USER: train_ro
  TRAIN_DB_PASSWORD: train_pass
