apiVersion: v1
kind: Service
metadata:
  name: training-postgres
  namespace: sql-trainer
spec:
  type: ClusterIP
  selector:
    app: training-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: training-postgres
  namespace: sql-trainer
spec:
  serviceName: training-postgres
  replicas: 1
  selector:
    matchLabels:
      app: training-postgres
  template:
    metadata:
      labels:
        app: training-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          # Устанавливаем ограничение на число соединений
          args: ["-c", "max_connections=30"]
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TRAIN_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TRAIN_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TRAIN_DB_PASSWORD
          readinessProbe:
            exec:
              command: ["pg_isready","-U","postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready","-U","postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: data
      securityContext:
        fsGroup: 999   # postgres
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
