apiVersion: v1
kind: Service
metadata:
  name: execution-api
  namespace: sql-trainer
spec:
  type: ClusterIP
  selector:
    app: execution-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-api
  namespace: sql-trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-api
  template:
    metadata:
      labels:
        app: execution-api
    spec:
      containers:
        - name: execution-api
          image: sql-trainer/execution-api:0.0.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # вот здесь мы и тянем БД
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://training-postgres.sql-trainer.svc.cluster.local:5432/training
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: execution-db
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: execution-db
                  key: DB_PASSWORD
            - name: EXECUTION_AUTO_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: execution-config
                  key: EXECUTION_AUTO_LIMIT
            - name: EXECUTION_ALLOW_ONLY_SELECT
              valueFrom:
                configMapKeyRef:
                  name: execution-config
                  key: EXECUTION_ALLOW_ONLY_SELECT
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
